### ISSUE TITLE
Stakeholder List

### ISSUE THREAD

**Issue by AbrafoJ** [AbrafoJ/LACleanUPSites#1]
flo?

**Comment by floxyao** [comment]
1. Board of Directors: Matt and his management team
2. Third-Party: Lawyer/Attorney, Insurance guy
3. Suppliers: anyone who supplies us with resources
4. Any other investor
5. Government (might take interest due to our impact on sustainability)
6. Local/global communities who support sustainability
7. Customers: Individuals who use our technology
8. Competitors
9. Employees (us)

**Comment by floxyao** [comment]
10. The property owner and people who are related
11. Property-owners that are located near the contaminated site
12. Anyone who sets foot on the property
13. Anyone who sees our technology e.g. Geotracker employees
14. Anyone with an interest in sustainability technology
